include:
  - path: ./chain-A/docker-compose.yaml
  - path: ./chain-B/docker-compose.yaml

#services:
  # creating the private keys and genesis files
#  besu-init:
#    image: hyperledger/besu:latest
#    volumes:
#      - ./helloworld:/config
#    command:
#      - operator
#      - generate-blockchain-config
#      - --config-file=/config/qbftConfigFile.json
#      - --to=/config/networkFiles
#      - --private-key-file-name=priv_key
